version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - run:
        name: Installing dependencies
        command: |
          npm install --save

workflows:
  build_now:
    jobs:
      - build